# https://issuetracker.revi.xyz/u/dependabot
# for documentation link

version: 2
updates:

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    assignees:
      - "revi"
    # Dockerfiles are stored in `container/lighthouse-ci-server/.
    directory: "container/lighthouse-ci-server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Seoul"
    target-branch: "master"
    labels: []
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    assignees:
      - "revi"
    # Workflow files stored in the default location of `.github/workflows`.
    # You don't need to specify `/.github/workflows` for `directory`.
    # You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Seoul"
    target-branch: "master"
    labels: []
    # Maintain dependencies for NPM
  - package-ecosystem: "npm"
    assignees:
      - "revi"
    # npm packages are stored in the default location of `package.json`.
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Seoul"
    target-branch: "master"
    labels: []
