packages:
  - ./npm/eslint-config/
  - ./npm/prettier-config/
catalog:
  eslint: 9.28.0
  prettier: 3.5.3
onlyBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - protobufjs
  - re2
