packages:
  - ./npm/eslint-config/
  - ./npm/prettier-config/
catalog:
  eslint: 9.31.0
  prettier: 3.6.2
onlyBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - protobufjs
  - re2
