<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * The committed copy is an empty placeholder: the map hashes the contents of
 * every resource, and the font files are downloaded by `bin/fetch-fonts` at
 * install time, so a meaningful map cannot be generated ahead of time. Until
 * `bin/celerity map` runs, the extension renders nothing and pages keep their
 * default fonts.
 *
 * `PhutilBootloader` also picks this file up when it scans the extensions
 * directory for `.php` files. That is harmless -- it declares no symbols, so
 * nothing is registered -- and `CelerityPhysicalResources::loadMap()` includes
 * it again by path to read the array back.
 */
return array(
  'names' => array(),
  'symbols' => array(),
  'requires' => array(),
  'packages' => array(),
);
