---
name: Publish Package to npmjs

on:
  push:
    tags:
      - 'eslint-config@v*'
      - 'prettier-config@v*'

jobs:
  eslint-config:
    name: 'Publish eslint-config to npm'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: contains(github.ref_name, 'eslint-config@')
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - name: 'Setup node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - name: 'Install dependencies'
        run: pnpm install
      - name: 'Publish to npm'
        run: pnpm publish --provenance --access public
        working-directory: './npm/eslint-config'
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  prettier-config:
    name: 'Publish prettier-config to npm'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: contains(github.ref_name, 'prettier-config@')
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - name: 'Setup node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - name: 'Install dependencies'
        run: pnpm install
      - name: 'Publish to npm'
        run: pnpm publish --provenance --access public
        working-directory: './npm/prettier-config'
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
