---
name: 'PHP Syntax Check'
on:
  push:
    paths:
      - '**.php'
    tags-ignore:
      - 'eslint-config@v*'
      - 'prettier-config@v*'
  pull_request:
  workflow_dispatch:

jobs:
  phpsyntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PHP Basic Syntax Check
        run: php -l ${{ github.workspace }}/PhabExt/PhabricatorCustomRobotsTxtController.php
