name: "PHP Syntax Check"
on:
  push:
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'
  workflow_dispatch:

jobs:
  phpsyntax:
    runs-on: ubuntu-latest
    steps:
      - name: "PHP Basic Syntax Check [robots.txt]"
        run: php -l PhabExt/PhabricatorCustomRobotsTxtController.php
      - name: "PHP Basic Syntax Check [time.php]"
        run: php -l time.php
